# Generated by Django 4.2.8 on 2025-12-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('exam_type', models.CharField(choices=[('JEE', 'JEE Main'), ('NEET', 'NEET'), ('BOARD', 'Board Exam')], max_length=10)),
                ('duration_minutes', models.IntegerField(help_text='Test duration in minutes')),
                ('total_questions', models.IntegerField()),
                ('is_featured', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_previous_year', models.BooleanField(default=False)),
                ('subjects', models.JSONField(default=list, help_text='List of subjects covered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='questions_difficu_9744d0_idx',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='api_questio_subject_cad2e5_idx',
            old_name='questions_subject_d0b933_idx',
        ),
        migrations.AlterField(
            model_name='question',
            name='chapter',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty'], name='api_questio_difficu_b6056a_idx'),
        ),
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
        migrations.AddField(
            model_name='mocktest',
            name='questions',
            field=models.ManyToManyField(related_name='mock_tests', to='api.question'),
        ),
        migrations.AddIndex(
            model_name='mocktest',
            index=models.Index(fields=['exam_type', 'is_featured'], name='api_mocktes_exam_ty_cbd368_idx'),
        ),
    ]
