# Generated by Django 4.2.8 on 2025-12-03 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_question_chapter_id_question_image_urls_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('selected_index', models.IntegerField()),
                ('attempted_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='api.user')),
            ],
            options={
                'db_table': 'question_attempts',
                'ordering': ['-attempted_at'],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
