# Generated by Django 4.2.8 on 2025-12-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_questionattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='chapter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testresult',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
