# Generated by Django 4.2.8 on 2025-12-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_testresult_chapter_testresult_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('DAILY_PRACTICE', 'Daily Practice'), ('MOCK_TEST_MASTER', 'Mock Test Master'), ('YEARLY_ELITE', 'Yearly Elite')], max_length=20),
        ),
    ]
