# Generated by Django 4.2.8 on 2025-12-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_subscriptionplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('DAILY_PRACTICE', 'Daily Practice'), ('MOCK_TEST_MASTER', 'Mock Test Master'), ('YEARLY_ELITE', 'Yearly Elite'), ('CHAPTER_UNLOCK', 'Chapter Wise Practice'), ('CHAPTER_MOCK_COMBO', 'Chapter + Mock Combo')], max_length=20),
        ),
    ]
