# Generated by Django 4.2.8 on 2025-12-04 07:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_practice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='max_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DailyPracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('practice_type', models.IntegerField(choices=[(25, 'Daily 25'), (50, 'Daily 50')])),
                ('is_completed', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attempts', to='api.user')),
            ],
            options={
                'db_table': 'daily_practice_attempts',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('user', 'date', 'practice_type')},
            },
        ),
    ]
