# Generated by Django 4.2.8 on 2025-12-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_current_streak_user_last_practice_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPracticePaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('practice_type', models.IntegerField(choices=[(25, 'Daily 25'), (50, 'Daily 50')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questions', models.ManyToManyField(related_name='daily_papers', to='api.question')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'practice_type')},
            },
        ),
    ]
